### ISSUE TITLE
Questions about the pipeline of the essay

### ISSUE THREAD

**Issue by HZIH** [jingyang2017/AU-Net#2]
The author has done a really great job, I am wondering whether the sequence of the training phase is 
1. Train AUnet w/o VAE
2. Train VAE
3. Train AUnet+VAE

**Comment by jingyang2017** [comment]
I think you are correct:
1. Train AUnet w/o VAE
2. Train VAE
3. Train AUnet+VAE (load 1 or not)
4. Train AUnet+VAE+TDN (load 3 or not)

**Comment by HZIH** [comment]
What's the meaning for (load 1 or not) and (load 3 or not). I guess you mean that load the weight in the first step and the weight in the third step.
Moreover, If your pipeline is what we mentioned above, the code for function data_load is not correct, especially in the train_vae.py. The dataLoader there return data and label, but actually the data_load function should output a dict.

**Comment by jingyang2017** [comment]
Yes. It is for load weights. The current data_load is for training AUnet+VAE+TDN. If you want to return data and label, you can rewrite the code.
